# Generated by Django 2.2.5 on 2021-05-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_auto_20210501_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasma',
            name='donor_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.Location', verbose_name='Donor Location'),
        ),
    ]
