# Generated by Django 2.2.5 on 2021-05-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcuBedBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Decline', 'Decline')], default='Pending', max_length=15, verbose_name='Icu Bed Booking Status')),
            ],
        ),
        migrations.CreateModel(
            name='MakeAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_description', models.CharField(max_length=254, verbose_name='What Is Your Problem')),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Decline', 'Decline')], default='Pending', max_length=15, verbose_name='Appointment Status')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('doctor_checkup', models.CharField(choices=[('Checked', 'Checked'), ('Not Checked', 'Not Checked')], default='Not Checked', max_length=15, verbose_name='Doctor Check Up Status')),
            ],
        ),
        migrations.CreateModel(
            name='OxygenCylinderBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Decline', 'Decline')], default='Pending', max_length=15, verbose_name='Oxygen Cylinder Booking Status')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Decline', 'Decline')], default='Pending', max_length=15, verbose_name='Vaccine Status')),
                ('nid_image', models.ImageField(upload_to='vaccine_nid_image', verbose_name='NID Image')),
                ('first_dos', models.DateField(blank=True, null=True, verbose_name='Vaccine First Dos')),
                ('second_dos', models.DateField(blank=True, null=True, verbose_name='Vaccine Second Dos')),
                ('hospital_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='SuperAdmin.Hospital', verbose_name='Hospital Name')),
            ],
        ),
    ]
